[package]
name = "hping-rs"
version = "1.3.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
pnet = "0.31.0"
pnet_base = "0.31.0"
pnet_datalink = "0.31.0"
pnet_packet = "0.31.0"
pnet_transport = "0.31.0"
rand = "0.8.5"
icmp = "0.3.0"
icmp-socket = "0.2.0"