name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          #- x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build --target ${{ matrix.target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hping-rs-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hping-rs*

      - name: Publish release
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: softprops/action-gh-release@v1
        with:
          files: >
            target/${{ matrix.target }}/release/hping-rs*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
